### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cdimascio** [hotmeatballsoup/dotenv-java#2]
Nice package :) I'm considering using it, but it requires a license. Can you provide one?

**Comment by hotmeatballsoup** [comment]
Hi @cdimascio 

This repo was one of my first git projects when I was young & stupid and I ended up getting it quasi-functional and then abandoned it altogether. I should have never made it a public repo!

Feel free to shamelessly steal/borrow/refactor any code you like, however just some food for thought:

I realize in hindsight that this project was sort of a non-starter. My *personal opinions* (feel free to disagree) have shifted to just using config files. I agree with a lot of 12-factor principles but Java's implementation (or limitations with, depending on how you view the problem!) of environment variables basically precludes you from having a standard way of injecting them into an app.

This project requires you to provide a `dotenv` config file. And its limited to key-value pairs. Why not just use a JSON/YAML/etc. config file? Doh!

Feel free to keep going down this path and take my code and use it for good or evil. Happy coding!

**Comment by cdimascio** [comment]
@hotmeatballsoup thanks for the note. given, i still have this need, I took your advice (as well as some inspiration) and created a similar project.  https://github.com/cdimascio/java-dotenv
thanks!
